docker:
  - image: 'cimg/base:stable'
steps:
  - slack/notify:
      custom: |
        {
          "blocks": [
            {
              "type": "section",
              "fields": [
                {
                  "type": "plain_text",
                  "text": ${CICD_MESSAGE_2},
                  "emoji": true
                }
              ]
            }
          ]
        }
      event: always
