version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  generate-and-run-circleci:
    docker:
      - image: 'circleci/circleci-cli:latest'
    steps:
      - circleci-cli/install
      - checkout
      - run:
          command : |
            cd .circleci
            circleci config pack config > generated.yml
      - continuation/continue:
          configuration_path: .circleci/generated.yml

workflows:
  build:
    jobs:
      - generate-and-run-circleci
