version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.3.1
  circleci-cli: circleci/circleci-cli@0.1.9

jobs:
  use-executor:
      executor: circleci-cli/default
      steps:
        - run: echo "this job is using the orb's default executor"
        
  generate-and-run-circleci:
    docker:
      - image: 'circleci/circleci-cli:latest'
    steps:
      - circleci-cli/install
      - checkout
      - run:
          command : |
            cd .circleci
            circleci config pack config > generated.yml
      - continuation/continue:
          configuration_path: .circleci/generated.yml

workflows:
  build:
    jobs:
      - use-executor
      - generate-and-run-circleci
